#!/usr/bin/env bash
# Build the explicit environment contract shared by launch and staleness checks.

resolve_deployment_child_environment() {
  DEPLOYMENT_CHILD_MANAGED_BOT_LOGINS=$(printf '%s' "$MANAGED_BOT_LOGINS" | "$PYTHON" -c \
    'import json,sys; print(",".join(json.load(sys.stdin)))') || return 1
  DEPLOYMENT_CHILD_AUTHORIZED_LOGINS=$(printf '%s' "$AUTHORIZED_LOGINS" | "$PYTHON" -c \
    'import json,sys; print(",".join(json.load(sys.stdin)))') || return 1
  DEPLOYMENT_CHILD_CREDENTIAL_SOURCE=$(printf '%s' "$GITHUB_CREDENTIAL_PROVIDER_CONFIGURATION" \
    | "$PYTHON" -c 'import json,sys; print(json.load(sys.stdin)["source"])') || return 1
  DEPLOYMENT_CHILD_REAL_GH="${FKST_GITHUB_REAL_GH:-${REAL_GH:-}}"
  DEPLOYMENT_CHILD_CREDENTIAL_RESOLVER="${FKST_GITHUB_CREDENTIAL_RESOLVER:-${GITHUB_CREDENTIAL_RESOLVER:-}}"
  DEPLOYMENT_CHILD_ENVIRONMENT=(
    BIN="$BIN" FKST_CARGO="$CARGO" FKST_PYTHON="$DEPLOYMENT_PYTHON"
    FKST_ENGINE_SOURCE_GIT="$ENGINE_GIT_URL"
    FKST_GITHUB_CREDENTIAL_HELPER="$GITHUB_CREDENTIAL_PROVIDER"
    FKST_GITHUB_CREDENTIAL_SOURCE="$DEPLOYMENT_CHILD_CREDENTIAL_SOURCE"
    FKST_GITHUB_CREDENTIAL_RESOLVER="$DEPLOYMENT_CHILD_CREDENTIAL_RESOLVER"
    FKST_GITHUB_REAL_GH="$DEPLOYMENT_CHILD_REAL_GH" FKST_GITHUB_REPO="$REPO"
    FKST_GITHUB_WRITE=1
    FKST_GITHUB_CLAIM_MODE="$CLAIM_MODE" FKST_GITHUB_CLAIM_LABEL_EXCLUSIVE="$CLAIM_LABEL_EXCLUSIVE"
    FKST_RATE_POOL_ROOT="$RATE_POOL" FKST_GITHUB_BOT_LOGIN="$BOT"
    FKST_DEVLOOP_MANAGED_BOT_LOGINS="$DEPLOYMENT_CHILD_MANAGED_BOT_LOGINS"
    FKST_GITHUB_AUTHORIZED_LOGINS="$DEPLOYMENT_CHILD_AUTHORIZED_LOGINS"
    FKST_GITHUB_AUTHORIZE_ORG_MEMBERS="$AUTHORIZE_ORG_MEMBERS"
    FKST_GITHUB_AUTHORIZE_REPO_COLLABORATORS="$AUTHORIZE_REPO_COLLABORATORS"
    FKST_DEVLOOP_UPSTREAM_BRANCH="$UPSTREAM_BRANCH"
    FKST_DEVLOOP_INTEGRATION_BRANCH="$INTEGRATION_BRANCH"
    FKST_DEVLOOP_ROLLUP_MERGE="$ROLLUP_MERGE"
    FKST_OPS_GITHUB_DEVLOOP_PROFILE="$GITHUB_DEVLOOP_PROFILE"
    FKST_WORKTREE_GC_REMOVE=1 PATH="$DEPLOYMENT_CHILD_PATH"
  )
  if [ -n "${LOCAL_TEST_COMMAND:-}" ]; then
    DEPLOYMENT_CHILD_ENVIRONMENT+=(
      FKST_DEVLOOP_LOCAL_TEST_COMMAND="$LOCAL_TEST_COMMAND"
    )
  fi
}

deployment_child_environment_sha256() {
  {
    printf '%s\0' "${DEPLOYMENT_CHILD_ENVIRONMENT[@]}"
    printf '%s\0' \
      "PLATFORM_PACKAGES=${PLATFORM_PKGS:-}" \
      "PACKAGE_SOURCES=${DECLARED_PACKAGE_SOURCES:-[]}"
  } | "$PYTHON" -c '
import hashlib
import sys

print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())
'
}
